import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { TanstackProvider } from './providers/TanstackProvider';
import { NextuiProvider } from './providers/NextuiProvider';
import { LocaleProvider } from '@/i18n/LocaleProvider';
import { getLocale } from '@/i18n/server';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const locale = getLocale();
	return (
		<html lang={locale || 'en-US'}>
			<body className={inter.className}>
				<LocaleProvider value={locale}>
					<TanstackProvider>
						<NextuiProvider>{children}</NextuiProvider>
					</TanstackProvider>
				</LocaleProvider>
			</body>
		</html>
	);
}
